package com.eve.marketwatch.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(
        tableName = "eve_marketwatch_item_watch"
)
public class ItemWatch {

    private String id;
    private int characterId;
    private long locationId;
    private int typeId;
    private String typeName;
    private long threshold;
    private boolean triggered;
    private boolean mailSent;
    // status process
    // triggered=false/mailSent=false -> triggered=true/mailSent=false -> triggered=true/mailSent=true -> triggered=mailSent=false
    //         base status                          WatchChecker                  MailSender                   WatchChecker

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(
            attributeName = "id"
    )
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public long getLocationId() {
        return locationId;
    }

    public void setLocationId(long locationId) {
        this.locationId = locationId;
    }

    public int getCharacterId() {
        return characterId;
    }

    public void setCharacterId(int characterId) {
        this.characterId = characterId;
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }

    public long getThreshold() {
        return threshold;
    }

    public void setThreshold(long threshold) {
        this.threshold = threshold;
    }

    public boolean isTriggered() {
        return triggered;
    }

    public void setTriggered(boolean triggered) {
        this.triggered = triggered;
    }

    public boolean isMailSent() {
        return mailSent;
    }

    public void setMailSent(boolean mailSent) {
        this.mailSent = mailSent;
    }

    public void reset() {
        triggered = false;
        mailSent = false;
    }

    @Override
    public String toString() {
        return "ItemWatch{" +
                "characterId=" + characterId +
                ", locationId=" + locationId +
                ", typeId=" + typeId +
                ", typeName='" + typeName + '\'' +
                ", threshold=" + threshold +
                ", triggered=" + triggered +
                ", mailSent=" + mailSent +
                '}';
    }
}
